### ISSUE TITLE
es6-modules: constraints on registration order / waiting on registration

### ISSUE THREAD

**Issue by rictic** [ruphin/gluonjs#1]
If `<foo-elem>` depends on `<bar-elem>` it probably needs some way to wait for `<bar-elem>` to be defined.

One simple way to do this would be to order the `customElements.define` calls by the order in which `Gluon.define` calls are made. You still get parallel requests for templates, so initial load performance would not suffer much at all, and pages would behave much more consistently.

I think it'd be useful to also be able to wait for all existing elements registered with `Gluon.define` to be registered. e.g. through code like:

```js
import './my-app/my-app.js';
import {Gluon} from './gluon/gluon.js';

Gluon.allReady().then(() => {
  document.querySelector('my-app').doSomething();
});
```

**Comment by ruphin** [comment]
The `customElements.define` calls are already guaranteed in-order, since the ES6 module loading system will execute the scripts in the correct dependency order. This was one of the first issues I ran into, with elements configuring their children before they were loaded. :)

Having an `allReady()` callback is a good idea. I'll look into if I can somehow detect if everything has been loaded. Probably by deferring the `loadResource()` calls, so the module loader will queue all the element registrations, and we can simply fire the callback when the `RESOURCEQUEUE` is empty.

**Comment by rictic** [comment]
Oh! I skimmed too fast and passed over how `RESOURCEQUEUE` was being used. Yeah, you've got this handled :)
